services:
  comprasapp-api:
    build: .
    container_name: comprasapp-api
    entrypoint: sh ./.docker/entrypoint.sh
    environment:
      PORT: 3000
    ports:
      - 3000:3000
    volumes:
      - .:/usr/node/comprasapp
    extra_hosts:
      - host.docker.internal:host-gateway
