POST http://localhost:3000/signup
Content-Type: application/json

{
  "name": "Haliane Ferreira Pessoa Nascimento",
  "email": "halianepessoa20@gmail.com",
  "password": "anypassword",
  "confirmationPassword": "anypassword"
}
###

POST http://localhost:3000/auth
Content-Type: application/json

{
  "email": "halianepessoa20@gmail.com",
  "password": "anypassword"
}
###
